ALTER TABLE `matches`
	DROP COLUMN `data`;

ALTER TABLE `matches`
	DROP COLUMN `turn`;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
DROP TABLE `results`;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
